require 'sinatra/base'

# 10kb Testserver
#
class ServerOne < Sinatra::Base
  get '/' do
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices, ipsum quis bibendum dignissim, tellus eros placerat nisi, dapibus blandit lectus dui non risus. Integer dui lectus, suscipit non nulla sit amet, iaculis rutrum nulla. Curabitur vehicula in libero facilisis porta. Proin commodo ante nec volutpat hendrerit. Sed dapibus scelerisque aliquet. In hac habitasse platea dictumst. Donec vitae tristique quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus tincidunt eu massa nec aliquam.

Sed aliquet enim erat, vitae condimentum ipsum tristique eu. Pellentesque iaculis nisl nibh, ac feugiat felis vestibulum eget. Phasellus ut condimentum enim, et suscipit augue. Integer at dui nec dui commodo volutpat sit amet a mi. In facilisis augue nunc, vel egestas nisl eleifend id. Praesent sed tellus vitae nisi venenatis malesuada non eget dui. Aenean nec lorem vel velit ultricies vulputate sed eget metus. In vel tristique dolor. Sed odio libero, dignissim a tellus quis, bibendum tincidunt orci. Maecenas mattis, ante at porta euismod, elit mauris varius odio, tristique gravida lorem lectus at lacus. Mauris ut interdum nulla. Mauris eget dui id purus ornare luctus.

Pellentesque feugiat fermentum risus, et sodales neque interdum at. Vestibulum a tempus odio. Fusce eu lorem dictum, cursus sapien et, fringilla leo. Donec ultricies, elit sit amet venenatis mollis, neque dui ultricies eros, eu hendrerit nulla lorem eget lorem. Ut vestibulum mi tempus odio tempus, vel aliquet libero condimentum. Vivamus sodales lacinia commodo. Praesent convallis sit amet massa quis blandit. Integer lobortis, metus eu venenatis vulputate, metus turpis mattis nibh, et faucibus mauris mauris nec magna. Fusce volutpat, metus vitae semper semper, tortor arcu ultrices leo, vitae mattis felis massa sit amet erat. Phasellus vitae posuere dui. Mauris ultrices interdum libero, ac porta magna tristique sed. Vivamus nulla enim, cursus vel sem vel, sollicitudin ornare lectus. Sed tristique lobortis ipsum, nec tristique purus vestibulum non. Nulla et molestie metus. Nullam id tortor gravida, cursus mauris ut, facilisis nunc.

Duis interdum quam quis orci volutpat iaculis. Aliquam non commodo metus. Vestibulum sit amet bibendum nulla. Nam purus orci, dapibus vitae pharetra eget, dapibus at risus. Quisque in convallis urna. Quisque pulvinar, nisi nec sodales viverra, turpis lectus placerat justo, at aliquam velit velit quis turpis. Etiam iaculis elit et purus venenatis, sed ullamcorper leo tincidunt. Donec vulputate ornare ipsum id iaculis. Nunc vitae quam nulla. Aenean sit amet nisi vitae eros aliquet volutpat. Nunc a pharetra odio. Aliquam ornare scelerisque purus rutrum venenatis.

Fusce euismod magna quis accumsan vestibulum. Duis justo justo, placerat blandit adipiscing et, gravida nec ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque arcu elit, mattis rhoncus magna quis, luctus rutrum ligula. Integer a risus fermentum, consequat odio vel, tempor diam. Mauris venenatis risus at turpis molestie, vel sodales augue tincidunt. Ut eget dui tellus. Curabitur vel metus massa. Curabitur iaculis non lorem et posuere. Vestibulum non elit magna.

Aliquam tempus tortor vitae lacus bibendum sodales vel eu turpis. Maecenas aliquam tellus sed ipsum adipiscing placerat. Phasellus laoreet mauris non felis porttitor commodo. Pellentesque tempor pellentesque tempor. Ut tempor, velit in volutpat gravida, mi sem adipiscing lacus, et vestibulum arcu nisl ut mauris. Nullam eros mauris, interdum non nibh non, consequat pretium dui. Aliquam egestas, dui posuere congue euismod, leo dui commodo metus, ut ornare nunc orci id libero. Sed at ligula nec risus cursus malesuada sit amet eu nulla. In laoreet sem augue, non posuere leo fermentum ut. Ut porttitor, quam eget sollicitudin aliquet, orci enim ultrices orci, eu pretium nulla quam id orci. Sed risus metus, elementum at lacinia in, gravida eget purus. Donec nec vehicula arcu, a congue diam. Suspendisse potenti. Phasellus varius rutrum dolor, quis ornare massa consequat ac. Pellentesque nibh diam, semper non fringilla at, ultricies ac massa.

Phasellus porta interdum mi vel elementum. Suspendisse vulputate ac magna a congue. Maecenas gravida ut leo at porttitor. Etiam interdum egestas libero. Phasellus vel congue tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris viverra sem purus, a feugiat leo faucibus id. Nullam nec est molestie, laoreet nulla id, interdum mauris. Aenean ultrices libero id nulla gravida euismod. Aliquam fermentum quam ut magna cursus, non eleifend quam fermentum.

Vivamus metus velit, malesuada ac quam at, tempor venenatis nibh. Morbi vel odio imperdiet, bibendum dui nec, imperdiet eros. Donec placerat mauris sed metus eleifend feugiat. In pulvinar arcu urna, tempus molestie quam varius eget. Aliquam viverra orci et arcu suscipit vestibulum. Fusce id placerat quam. Nullam fermentum massa a placerat dignissim. Cras sollicitudin, nisi sed laoreet pretium, dolor leo semper lorem, vitae varius arcu dolor a nunc. Suspendisse sit amet dolor vitae massa lacinia imperdiet. Fusce ac feugiat sem. In viverra orci in vulputate euismod.

Curabitur ornare malesuada dolor, sed adipiscing nunc. Suspendisse vel diam nulla. Donec ut elit a mi auctor gravida. Fusce nec massa mi. In interdum porta tortor sit amet accumsan. Cras auctor, ipsum vitae porta tempor, diam turpis dictum mi, nec mollis tellus libero dignissim justo. Mauris eget porttitor elit, et rhoncus arcu.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ullamcorper iaculis ante ac lacinia. Aenean eget ipsum viverra, semper magna eget, congue sapien. Etiam tristique, lectus ut aliquet sodales, felis neque sodales magna, ac rhoncus tellus est nec enim. Proin aliquet massa sit amet lacus interdum feugiat. Suspendisse libero ipsum, facilisis sit amet consectetur et, tristique nec lectus. Duis fermentum quam lacus, ac hendrerit mi porttitor a. Quisque at sodales nibh, non sodales dolor. Morbi placerat velit sit amet erat convallis ultricies. Sed non lacus elit.

Etiam eleifend bibendum est, non volutpat leo rhoncus sed. Morbi ligula leo, fermentum sed turpis quis, fringilla pellentesque augue. Curabitur sodales rhoncus elit vel accumsan. Aliquam hendrerit in mauris quis imperdiet. Donec gravida ac felis in dapibus. Fusce non leo ut turpis aliquet sollicitudin a non est. Nunc a neque felis. Morbi ac hendrerit orci, eu convallis neque.

Donec interdum arcu ac pellentesque pellentesque. Nullam tincidunt vel velit vel gravida. Vestibulum ut quam et mauris ultrices feugiat. Nullam pellentesque ultricies ipsum non dapibus. Morbi tempor convallis elementum. Sed eget lorem ac dolor tincidunt dictum. Aliquam erat volutpat. Phasellus quis nulla ac neque tincidunt consectetur quis id ipsum. Cras eget est libero.

Duis cursus aliquet ligula in mollis. Nulla eget erat vel est lobortis lobortis a in urna. Nam fermentum suscipit dolor et tempor. Quisque at tristique dolor, eu fringilla neque. Etiam quis sapien at lacus auctor faucibus ac at libero. Praesent pulvinar sapien mi, vitae aliquam est fermentum non. Aliquam ac posuere libero. Nunc bibendum mauris metus, a blandit massa ultrices eu. Nunc placerat risus dolor, at aliquet metus ultrices at. Suspendisse iaculis interdum pellentesque.

Sed tempor nisl massa, non ornare diam elementum a. Mauris tempus massa justo, non fermentum lectus volutpat ut. Proin in massa quis arcu euismod vulputate sit amet vitae massa. Donec convallis dui eu massa blandit viverra. Curabitur et nunc vel purus auctor viverra eget nec lacus. Aliquam erat volutpat. Nam condimentum nunc nisi, nec congue neque auctor non. Donec mollis ante nec ligula eleifend, eu semper dui ullamcorper. Sed non magna ligula. Aenean id tortor et felis vehicula gravida sit amet vitae tortor. Morbi laoreet, urna vel viverra commodo, massa mi dictum nibh, nec tempus velit eros a leo. Nunc dapibus placerat felis, eu ultricies nunc ultrices in. Nam auctor libero eu mauris imperdiet, sit amet interdum libero convallis. Duis pulvinar pellentesque sollicitudin. Nam vestibulum nisl at tempus semper. Fusce non vulputate urna.

Proin tortor orci, luctus sit amet egestas dictum, accumsan ac erat. Mauris placerat nulla justo, et posuere turpis ultricies a. Morbi malesuada, odio non volutpat sagittis, libero est facilisis ante, at commodo dolor augue at quam. In mattis ipsum id egestas pulvinar. Maecenas rutrum tortor augue, at porttitor odio tincidunt eu. Morbi purus ipsum, volutpat ut massa a, aliquet elementum turpis. Praesent eget quam in eros pellentesque tempor nec vel magna. Mauris id enim sodales, iaculis lorem id, mattis augue. Phasellus ultrices laoreet purus sit amet porta. Quisque vulputate urna justo, quis vestibulum augue vulputate ultrices. Praesent laoreet sem sed diam volutpat, laoreet consequat sapien lobortis. Nullam ultrices volutpat risus, quis congue nulla congue a. Nunc pretium tortor nec pretium cursus. Aenean eget vehicula odio, a egestas orci.

Etiam scelerisque neque vitae mauris tincidunt, in lobortis nisi molestie. Nunc nisl velit, cursus varius congue et, consectetur sit amet ligula. Curabitur ipsum lectus, dignissim a ultrices id, semper non odio. Curabitur pharetra elementum sapien, vitae fringilla dolor tristique sit amet. Nam pharetra tellus justo, ut tempus neque varius nec. Nullam luctus quam vel nunc iaculis sagittis. Pellentesque at est massa. Nam ac sodales tortor.

Duis elit lacus, viverra sit amet tortor posuere, ornare viverra nunc. Vestibulum ut faucibus massa, vitae mollis lectus. Duis suscipit feugiat rutrum. Nam venenatis turpis sit amet justo convallis, in sollicitudin dolor interdum. Cras lacus risus, mattis quis faucibus quis, accumsan eget purus. Morbi a est quis lorem interdum malesuada quis a lorem. Nullam eu elit mauris. Sed pellentesque eleifend mollis. Etiam et lacus libero.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse commodo massa quis consequat posuere. Etiam eleifend ut nulla sagittis laoreet. Curabitur nulla lectus, consequat ac accumsan sit amet, placerat vitae massa. Donec a lectus dignissim, hendrerit tortor vitae, molestie sapien. Curabitur interdum pulvinar ultricies. Aenean vitae dignissim ipsum.

Mauris suscipit ullamcorper justo eu condimentum. Aliquam sed nisi nec risus tempus vulputate vel sed neque. Donec mollis ac nunc non vehicula. Vivamus vitae tincidunt lacus, vitae tempus diam. Phasellus eu nisi sollicitudin sapien congue ullamcorper. Phasellus mollis lectus sed semper egestas. Suspendisse hendrerit velit nisl, et dictum sem imperdiet eget. Nam luctus mi fringilla, rhoncus sem tempus, venenatis elit. Duis ullamcorper iaculis augue id venenatis. Vivamus convallis cursus velit vel iaculis. Ut rutrum feugiat ipsum bibendum porta. Donec eget tortor vitae erat volutpat sagittis ut pellentesque nunc.

Morbi id consectetur leo. Vestibulum massa massa, mattis quis congue quis, porta sit amet ligula. Aliquam adipiscing hendrerit felis, eu commodo neque malesuada sed. Aliquam erat volutpat. Praesent ut nisi non tortor tincidunt mattis. Fusce vulputate laoreet placerat. Maecenas dapibus facilisis interdum. Morbi a lobortis velit.

Pellentesque tincidunt mi quis metus imperdiet, in luctus lorem blandit. Nulla accumsan neque vitae libero tempus, sit amet consectetur justo semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse congue arcu nisl, et fringilla sem viverra nec. Cras sed dolor gravida, lacinia metus non, ultricies nisl. Vestibulum turpis neque, placerat condimentum aliquet vitae, dapibus non lectus. Aenean arcu ipsum, dictum id eleifend a, facilisis non dui. Morbi ultricies nunc vel magna rhoncus venenatis. Donec id varius mi. Sed felis mauris, pretium et urna et, laoreet eleifend tellus.

Nullam varius suscipit arcu. Vivamus eleifend euismod lorem a blandit. Sed at dapibus massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus imperdiet, massa ac dignissim lacinia, nunc ipsum convallis massa, et facilisis arcu felis id metus. Fusce ac orci dolor. Etiam bibendum eros eu ante fringilla placerat sit amet in nisl. Integer in ullamcorper neque. Mauris id lacus ac dui lobortis tempus a ut mauris. Vestibulum urna ante, ullamcorper vel hendrerit vel, euismod sit amet nisl.

Aliquam vel scelerisque lorem, ut accumsan tellus. Suspendisse rutrum vestibulum nisi nec convallis. In ligula urna, bibendum at auctor vel, cursus id nunc. Cras id libero id lorem vestibulum feugiat eget ac diam. Fusce in ante neque. Fusce est nisl, aliquet at placerat sit amet, tincidunt id nisi. Aliquam ligula enim, egestas et tincidunt ac, pretium at sem. Aenean et purus ultricies lacus pulvinar sagittis quis ac mauris.

Mauris a imperdiet urna. Fusce sed dictum augue. Sed in tempor nibh. Etiam nec mi magna. Maecenas id ligula a metus bibendum convallis elementum in nisi. Vivamus lobortis vestibulum lectus, non rhoncus ipsum laoreet vitae. Nunc eget viverra lorem, eget scelerisque tellus. Duis et accumsan augue, vel tempor sem. Nullam ullamcorper cursus urna sit amet vehicula. Donec lacinia orci vitae arcu hendrerit elementum. Nulla scelerisque ultrices lorem eget hendrerit. Cras blandit elit a dui sagittis lobortis.

In quam ante, molestie id libero non, euismod gravida diam. Nulla quis nibh quis turpis rutrum feugiat nec eget mauris. Duis sit amet turpis tortor. Integer sem massa, fermentum sit amet pharetra in, luctus in lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla eros nibh, feugiat at interdum ac, tristique congue turpis. Phasellus nisl metus, dignissim quis leo accumsan, suscipit commodo enim. Aliquam sit amet iaculis enim. Proin suscipit risus non dui volutpat aliquam. Vivamus purus erat, lacinia sit amet eros eu, scelerisque volutpat risus. Phasellus pellentesque porta libero, ac interdum urna imperdiet ut. Donec sit amet ligula neque. Nam et velit id lorem malesuada pellentesque et eget nunc. Vestibulum consequat commodo feugiat. Morbi venenatis massa nec leo adipiscing scelerisque.

In semper, sem vulputate viverra accumsan, odio odio pharetra eros, sit amet rhoncus turpis orci vitae quam. Etiam erat felis, aliquam rutrum odio a, interdum rutrum felis. Nulla hendrerit ut justo sed vestibulum. Quisque interdum massa neque, sit amet gravida arcu consequat a. Praesent a sem lectus. Duis ultrices tincidunt mi, a euismod lectus mattis tempus. Vestibulum odio quam, lobortis et est nec, egestas adipiscing odio. Praesent et mi risus. Suspendisse dignissim, velit sit amet ultricies vulputate, arcu ipsum ornare arcu, congue aliquet justo nisl laoreet tortor. Cras pulvinar felis id justo porttitor, sed malesuada elit facilisis. Donec dignissim odio vitae urna fringilla faucibus sed eu ipsum.

Duis in tempor ipsum. Curabitur dignissim, nisi et mattis commodo, est mauris elementum nulla, sit amet lacinia libero orci ut sapien. Donec ultricies molestie nisi a pulvinar. Nullam imperdiet nisl velit. Pellentesque non est et odio volutpat placerat. Nam eu magna id diam porttitor tincidunt. Phasellus malesuada nec dui sit amet vulputate. Phasellus ut facilisis est.

Aliquam vestibulum urna ac purus volutpat ultrices. Integer eu posuere mi, vitae tincidunt dui. In quam justo, luctus quis diam ac, tristique auctor tellus. Ut at arcu erat. Nullam vitae ante tincidunt, venenatis lectus in, iaculis tortor. Nulla et sem in risus porttitor semper a ac neque. Sed ac nisi dignissim, scelerisque lorem a, ornare purus. Curabitur quis nisl blandit, placerat mauris ut, blandit tellus. Morbi quam est, interdum ut augue sed, euismod tempus mauris. In dictum nibh non elit fermentum iaculis. In id elit sit amet justo euismod aliquet vitae quis orci. In dapibus nunc tortor, et suscipit magna blandit ut. In quis ornare eros, sit amet pharetra nibh.

Ut porttitor elit sit amet leo sollicitudin dignissim. Donec adipiscing purus a auctor aliquam. Suspendisse scelerisque, felis sit amet accumsan venenatis, est elit laoreet lectus, sed convallis ligula eros sed nisl. Nam tristique mi justo. Nullam pharetra pulvinar odio, eu lacinia neque aliquam in. Pellentesque nisl lacus, tempus eu elit vel, rutrum suscipit dolor. Mauris eget pretium risus. Nullam porta commodo urna ac sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sed nisl sit amet erat pretium sagittis.

In consequat semper eleifend. Vestibulum id viverra dui. In hac habitasse platea dictumst. Vivamus aliquet ante ut enim tristique euismod. Nam interdum orci ante. Nam a orci ut dolor egestas blandit. Nam et auctor risus. Etiam auctor, sapien nec facilisis dictum, magna purus tempus dui, sed malesuada augue nisi eget erat. Donec quis scelerisque ante, vel interdum ipsum. Donec semper ligula et lacus aliquam lacinia. Sed pharetra molestie dapibus. Donec pulvinar erat id velit vehicula faucibus.

In hac habitasse platea dictumst. Nunc dictum turpis vel condimentum feugiat. Nam vel facilisis libero. Ut bibendum, mauris at scelerisque laoreet, libero leo mollis ligula, ut accumsan risus mauris eu velit. Phasellus quis sodales risus. Maecenas eget lacinia massa, nec accumsan mauris. Etiam quis sagittis magna. Duis sapien velit, viverra et ante et, commodo interdum ligula. Morbi sit amet commodo risus. Fusce in nibh in neque faucibus dignissim. Etiam lacinia justo quis egestas condimentum. Integer dapibus, elit id gravida mattis, magna elit sagittis arcu, ac hendrerit velit leo nec neque.

Morbi sed lectus at diam molestie convallis. Duis at convallis tellus. Duis sodales, arcu non convallis molestie, purus nibh molestie massa, tempor cursus enim ante at nisl. Aliquam sed massa lorem. Cras adipiscing velit tincidunt justo semper, vel fermentum diam luctus. Proin ante turpis, auctor quis odio ut, volutpat ultrices diam. Duis a interdum neque, sit amet accumsan enim. Vivamus vehicula feugiat leo, vel tempus elit. Sed laoreet adipiscing suscipit.

In facilisis vestibulum est ut vulputate. Aliquam vehicula magna a ultrices dapibus. Sed eu tortor ut eros posuere bibendum euismod sed felis. Donec tempor metus quis tellus venenatis dapibus. Proin imperdiet at velit et sagittis. Aenean euismod porta lacus, et rutrum enim porta feugiat. Donec posuere risus nec mi dapibus, tristique fermentum urna tempor. Nunc nisi quam, rutrum et varius sed, viverra faucibus lacus. Pellentesque vulputate tempor orci at sollicitudin. Nulla sit amet malesuada justo, quis posuere lorem. Phasellus lorem libero, commodo quis porta malesuada, varius in quam. Cras tellus sem, malesuada nec molestie at, dignissim ac mauris. Aenean viverra ipsum at aliquet cursus. Nam porta eu ipsum quis facilisis. Suspendisse vel commodo risus. Ut malesuada metus accumsan egestas feugiat.

Nullam dapibus massa quis arcu cursus rhoncus. Fusce a nulla at lacus accumsan adipiscing vitae id tellus. Duis consequat erat sit amet felis congue viverra. Morbi sed est odio. Maecenas malesuada euismod ante, vitae fermentum quam fringilla at. Nullam congue elit in nisl aliquam semper. Fusce aliquam lacus eget fermentum euismod. Sed vitae arcu mauris.

Nullam congue dolor sed ligula gravida, nec lacinia dui tempus. Duis vitae tempus mi. Fusce feugiat est id fringilla vulputate. Mauris ultricies sem feugiat dolor cursus, eu semper libero molestie. Donec lacinia nulla urna, non molestie ante volutpat quis. Mauris mollis magna lacus, quis tristique metus aliquam vel. Ut eget tristique erat.

Duis fringilla nulla nec euismod consectetur. Maecenas sed turpis arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed auctor augue nec porta hendrerit. Fusce vitae cursus augue. Morbi urna sem, convallis bibendum faucibus ac, tincidunt et nibh. Cras lacinia, lorem eu vestibulum dignissim, ligula nisi consequat erat, eu placerat lacus sem at metus. Cras aliquet urna at nisi volutpat, id tincidunt lacus accumsan.

Aliquam euismod bibendum mauris. Sed pellentesque, lacus ut sagittis fermentum, diam nibh bibendum metus, ut porttitor libero urna vel sapien. Nunc non urna elementum, volutpat odio vitae, accumsan turpis. Sed pharetra, est non sodales gravida, lacus lacus egestas lacus, a consequat risus libero vitae magna. Sed non molestie felis, in cursus orci.
Sed amet." * 2

  end

  # start the server if ruby file executed directly
  run! if app_file == $0
end
